# Generated by Django 3.2.7 on 2022-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Payment type'),
        ),
    ]
